#!/bin/sh
nvim -u $HOME/.config/nvim/plugins.vim +PlugUpgrade +PlugInstall +PlugClean\! +qa
rm $HOME/dotfiles/config/nvim/autoload/plug.vim.old $HOME/.config/nvim/autoload/plug.vim.old
fc-cache -f -v
