#!/bin/bash

touch "$HOME"/.psqlrc.local

if [ ! -e "$HOME"/.config/nvim/autoload/plug.vim ]; then
  curl -fLo "$HOME"/.config/nvim/autoload/plug.vim --create-dirs \
      https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
fi
nvim -u $HOME/.config/nvim/plugins.vim +PlugUpgrade +PlugInstall +PlugClean\! +qa
rm $HOME/dotfiles/config/nvim/autoload/plug.vim.old $HOME/.config/nvim/autoload/plug.vim.old

fc-cache -f -v
